<a href="https://colab.research.google.com/github/kamalidoss/Nassau-Candy-Distributor-Analysis/blob/main/Nassau_Candy_Distributor_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Nassau Candy Distributor Analysis**

🚚 Factory-to-Customer Shipping Route Efficiency Analysis for Nassau Candy Distributor using Python, Pandas, Plotly, and Streamlit. This project analyzes shipping lead times, route performance, ship mode efficiency, and geographic bottlenecks to improve logistics operations and delivery reliability across U.S. regions.

**Objectives**

1. Analyze shipping lead times by calculating the time taken between order placement and shipment delivery across all customer locations.

2. Evaluate factory-to-customer route efficiency by identifying the fastest and slowest shipping routes based on average lead time.

3. Measure route performance using key metrics such as shipment volume, average lead time, lead time variability, and route efficiency scores.

4. Compare shipping methods to determine how different ship modes impact delivery speed and overall logistics performance.

5. Identify geographic bottlenecks by analyzing shipping delays across regions, states, and customer locations.

6. Assess the relationship between shipment volume and delivery performance to detect high-demand areas that may experience operational challenges.

7. Develop interactive visualizations and dashboards to provide real-time insights into shipping operations and route performance.

8. Support data-driven logistics decision-making by transforming shipment data into actionable recommendations for improving delivery reliability and operational efficiency.

9. Enhance customer satisfaction by identifying opportunities to reduce delays and improve shipping consistency across the distribution network.

10. Provide strategic recommendations for route optimization, resource allocation, and logistics planning to improve nationwide shipping performance.

# **Dataset Information**

1. Source - Dataset collected from unified mentor project portal

2. Location - United States

3. Year / Timeline : 2024 - 2026

4. Domain - E-Commerce

In [1]:
#importing Libraries

import numpy as np
import pandas as pd

# Visualization Libraries
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

#Searching text patterns
import re

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
#Loading the Dataset

url=('https://raw.githubusercontent.com/kamalidoss/Nassau-Candy-Distributor-Analysis/refs/heads/main/Raw%20Dataset.csv')

df=pd.read_csv(url)

In [3]:
#To view the data:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

**Dataset Features**
| Column Name | Description |
|------------|-------------|
| Row ID | Unique identifier for each record in the dataset |
| Order ID | Unique identifier assigned to each customer order |
| Order Date | Date on which the customer placed the order |
| Ship Date | Date on which the order was shipped to the customer |
| Ship Mode | Shipping method used for delivering the order |
| Customer ID | Unique identifier for each customer |
| Country/Region | Country or region where the customer is located |
| City | Customer's city location |
| State/Province | Customer's state or province |
| Postal Code | Customer's postal or ZIP code |
| Division | Product division/category (Chocolate, Sugar, Other, etc.) |
| Region | Geographical region of the customer |
| Product ID | Unique identifier for each product |
| Product Name | Name of the product ordered |
| Sales | Total revenue generated from the order |
| Units | Number of product units sold in the order |
| Gross Profit | Profit earned from the order after deducting cost from sales |
| Cost | Manufacturing or procurement cost of the product |

**Initial Exploratory Data Analysis (EDA)**

In [4]:
# Shape of dataset
df.shape

(10194, 18)

In [5]:
# Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), object(12)
memory usage: 1.4+ MB

In [6]:
# Statistical Summary
df.describe()

,Row ID,Customer ID,Sales,Units,Gross Profit,Cost
count,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,134468.961154,13.908537,3.791838,9.166451,4.742087
std,2942.898656,20231.483007,11.341020,2.228317,6.643740,5.061647
min,1.000000,100006.000000,1.250000,1.000000,0.250000,0.600000
25%,2549.250000,117212.000000,7.200000,2.000000,4.900000,2.400000
50%,5097.500000,133550.000000,10.800000,3.000000,7.470000,3.600000
75%,7645.750000,152051.000000,18.000000,5.000000,12.250000,5.700000
max,10194.000000,192314.000000,260.000000,14.000000,130.000000,130.000000

In [7]:
# Column Names
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name',
       'Sales', 'Units', 'Gross Profit', 'Cost'],
      dtype='object')

In [8]:
#View first 5 rows
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [9]:
#View last 5 rows
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
10189,10190,US-2024-143259-CHO-MIL-31000,30-12-2025,26-06-2030,Standard Class,143259,United States,New York City,New York,10009,Chocolate,Atlantic,CHO-MIL-31000,Wonka Bar - Milk Chocolate,9.75,3,6.33,3.42
10190,10191,US-2024-115427-CHO-NUT-13000,30-12-2025,26-06-2030,Standard Class,115427,United States,Fairfield,California,94533,Chocolate,Pacific,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,6.98,2,4.98,2.00
10191,10192,US-2024-156720-CHO-SCR-58000,30-12-2025,26-06-2030,Standard Class,156720,United States,Loveland,Colorado,80538,Chocolate,Pacific,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
10192,10193,US-2024-143259-CHO-TRI-54000,30-12-2025,26-06-2030,Standard Class,143259,United States,New York City,New York,10009,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,26.25,7,17.15,9.10
10193,10194,CA-2024-143500-CHO-SCR-58000,30-12-2025,26-06-2030,Standard Class,143500,Canada,Charlottetown,Prince Edward Island,C0A,Chocolate,Atlantic,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30

In [10]:
#Check Null Values
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [11]:
#Check Duplicate Records
df.duplicated().sum()

np.int64(0)

# **Step 1: Data Cleaning**

In [12]:
#Convert Dates

df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d-%m-%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%d-%m-%Y')

In [13]:
#Calculate Lead Time

df['Lead_Time'] = (
    df['Ship Date'] - df['Order Date']
).dt.days

In [14]:
#Remove Invalid Records

df = df[df['Lead_Time'] >= 0]

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Row ID            10194 non-null  int64
 1   Order ID          10194 non-null  object
 2   Order Date        10194 non-null  datetime64[ns]
 3   Ship Date         10194 non-null  datetime64[ns]
 4   Ship Mode         10194 non-null  object
 5   Customer ID       10194 non-null  int64
 6   Country/Region    10194 non-null  object
 7   City              10194 non-null  object
 8   State/Province    10194 non-null  object
 9   Postal Code       10194 non-null  object
 10  Division          10194 non-null  object
 11  Region            10194 non-null  object
 12  Product ID        10194 non-null  object
 13  Product Name      10194 non-null  object
 14  Sales             10194 non-null  float64
 15  Units             10194 non-null  int64
 16  Gross Profit      10194 non-null  float64
 17  Cost              10194 non-null  float64
 18  Lead_Time         10194 non-null  int64
 19  Factory           9877 non-null   object
 20  Route_State       9877 non-null   object
 21  Route_Region      9877 non-null   object
 22  Efficiency_Score  10194 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(4), object(13)
memory usage: 1.8+ MB

# **Step 2: Factory Mapping**

The dataset doesn't directly contain factory names.

Factory must be derived using Product Name.

In [15]:
factory_map = {
    "Wonka Bar - Nutty Crunch Surprise":"Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows":"Lot's O' Nuts",
    "Wonka Bar -Scrumdiddlyumptious":"Lot's O' Nuts",

    "Wonka Bar - Milk Chocolate":"Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel":"Wicked Choccy's",

    "Laffy Taffy":"Sugar Shack",
    "SweeTARTS":"Sugar Shack",
    "Nerds":"Sugar Shack",
    "Fun Dip":"Sugar Shack",
    "Fizzy Lifting Drinks":"Sugar Shack"
}

In [16]:
df["Factory"] = df["Product Name"].map(factory_map)

# **Step 3: Route Definition**

In [17]:
#Route by State

df["Route_State"] = (
    df["Factory"] + " → " +
    df["State/Province"]
)

In [18]:
#Route by Region

df["Route_Region"] = (
    df["Factory"] + " → " +
    df["Region"]
)

**KPI Dashboard**

Top row KPI cards:

In [19]:
# KPI 1 - Total Shipments

len(df)

10194

In [20]:
#KPI 2 - Average Lead Time

df["Lead_Time"].mean()

np.float64(1320.8418677653522)

In [21]:
#KPI 3 - Total Sales

df["Sales"].sum()

np.float64(141783.63)

In [22]:
#KPI 4 - Gross Profit

df["Gross Profit"].sum()

np.float64(93442.8)

In [23]:
#KPI 5 - Delay Frequency
#Threshold = 5 Days

(
(df["Lead_Time"] > 5).mean()
)*100

np.float64(100.0)

**Route Efficiency Analysis**

In [24]:
#Route Performance Table

route_perf = (
    df.groupby("Route_State")
    .agg({
        "Lead_Time":["mean","std","count"]
    })
)

In [25]:
#Top 10 Efficient Routes

route_perf.sort_values(
    ('Lead_Time','mean')
).head(10)

                                             Lead_Time
                                                  mean         std count
Route_State
Wicked Choccy's → Maine                     908.000000    0.000000     2
Sugar Shack → Delaware                      910.000000         NaN     1
Sugar Shack → Florida                      1031.000000  211.310199     3
Sugar Shack → Illinois                     1089.000000  257.386868     2
Wicked Choccy's → South Dakota             1152.000000  422.620397     3
Wicked Choccy's → Nevada                   1182.250000  226.373033    12
Lot's O' Nuts → Maine                      1213.500000  149.664625     6
Lot's O' Nuts → Newfoundland and Labrador  1216.166667  357.447292     6
Wicked Choccy's → Montana                  1221.857143  389.897606     7
Lot's O' Nuts → Virginia                   1229.486239  262.008609   109

In [26]:
#Bottom 10 Inefficient Routes

route_perf.sort_values(
    ('Lead_Time','mean'),
    ascending=False
).head(10)

                                Lead_Time
                                     mean         std count
Route_State
Sugar Shack → New Jersey           1642.0         NaN     1
Sugar Shack → Connecticut          1641.0         NaN     1
Wicked Choccy's → West Virginia    1639.0    0.000000     2
Lot's O' Nuts → North Dakota       1638.2    1.643168     5
Sugar Shack → Washington           1638.0         NaN     1
Sugar Shack → California           1638.0         NaN     1
Sugar Shack → Ohio                 1637.5    3.535534     2
Wicked Choccy's → North Dakota     1637.0    0.000000     2
Lot's O' Nuts → West Virginia      1637.0    2.828427     2
Lot's O' Nuts → Vermont            1492.4  200.285546     5

**Geographic Bottleneck Analysis**

In [27]:
#State-Level Delays

state_delay = (
    df.groupby("State/Province")
    ["Lead_Time"]
    .mean()
)

In [28]:
#Region Performance

region_perf = (
    df.groupby("Region")
    ["Lead_Time"]
    .mean()
)

**Ship Mode Analysis**

In [29]:
#Average Lead Time by Ship Mode

df.groupby("Ship Mode")["Lead_Time"].mean()

Ship Mode
First Class       1338.275840
Same Day          1333.442413
Second Class      1323.845376
Standard Class    1314.334641
Name: Lead_Time, dtype: float64

In [30]:
#Ship Mode vs Profit

df.groupby("Ship Mode").agg({
    "Sales":"sum",
    "Gross Profit":"sum",
    "Lead_Time":"mean"
})

                   Sales  Gross Profit    Lead_Time
Ship Mode
First Class     21319.39      14011.09  1338.275840
Same Day         7113.67       4700.73  1333.442413
Second Class    27860.22      18306.52  1323.845376
Standard Class  85490.35      56424.46  1314.334641

**Route Efficiency Score**

In [31]:
#Normalize Lead Time

max_lead_time = df['Lead_Time'].max()
df['Efficiency_Score'] = 100 - (df['Lead_Time'] / max_lead_time) * 100

In [32]:
max_time = df["Lead_Time"].max()

df["Efficiency_Score"] = (
100 -
(df["Lead_Time"]/max_time)*100
)

**Route Drill-Down Page**

In [33]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Product Name,Sales,Units,Gross Profit,Cost,Lead_Time,Factory,Route_State,Route_Region,Efficiency_Score
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,...,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,909,Wicked Choccy's,Wicked Choccy's → Texas,Wicked Choccy's → Interior,44.640682
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,909,Wicked Choccy's,Wicked Choccy's → Illinois,Wicked Choccy's → Interior,44.640682
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,909,Lot's O' Nuts,Lot's O' Nuts → Illinois,Lot's O' Nuts → Interior,44.640682
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,909,Lot's O' Nuts,Lot's O' Nuts → Illinois,Lot's O' Nuts → Interior,44.640682
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2026-07-05,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,...,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,912,Wicked Choccy's,Wicked Choccy's → Pennsylvania,Wicked Choccy's → Atlantic,44.457978

In [34]:
df["Lead_Time"].dtype

dtype('int64')

In [36]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Product Name,Sales,Units,Gross Profit,Cost,Lead_Time,Factory,Route_State,Route_Region,Efficiency_Score
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,...,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,909,Wicked Choccy's,Wicked Choccy's → Texas,Wicked Choccy's → Interior,44.640682
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,909,Wicked Choccy's,Wicked Choccy's → Illinois,Wicked Choccy's → Interior,44.640682
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,909,Lot's O' Nuts,Lot's O' Nuts → Illinois,Lot's O' Nuts → Interior,44.640682
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,909,Lot's O' Nuts,Lot's O' Nuts → Illinois,Lot's O' Nuts → Interior,44.640682
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2026-07-05,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,...,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,912,Wicked Choccy's,Wicked Choccy's → Pennsylvania,Wicked Choccy's → Atlantic,44.457978

In [37]:
df.to_csv("Raw Dataset.csv", index=False)